services:
  - type: web
    name: manuale-staff
    runtime: node
    plan: free
    buildCommand: npm install && git lfs pull
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
